apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11.2
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: selleo_db
        - name: POSTGRES_USER
          value: selleo
        - name: POSTGRES_PASSWORD
          value: Secret99
